version: '3.1'
services:
  zoo1:
    image: zookeeper
    ports:
      - 2181:2181
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS:  server.1=192.168.11.2:2888:3888;2181 server.2=192.168.11.3:2888:3888;2181 server.3=192.168.11.4:2888:3888;2181
      ZOO_ADMINSERVER_ENABLED: "false"
    networks:
      zookeeper-network:
        ipv4_address: 192.168.11.2 
  zoo2:
    image: zookeeper
    ports:
      - 2182:2181
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=192.168.11.2:2888:3888;2181 server.2=192.168.11.3:2888:3888;2181 server.3=192.168.11.4:2888:3888;2181
      ZOO_ADMINSERVER_ENABLED: "false"
    networks:
      zookeeper-network:
        ipv4_address: 192.168.11.3
  zoo3:
    image: zookeeper
    ports:
      - 2183:2181
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=192.168.11.2:2888:3888;2181 server.2=192.168.11.3:2888:3888;2181 server.3=192.168.11.4:2888:3888;2181
      ZOO_ADMINSERVER_ENABLED: "false"
    networks:
      zookeeper-network:
        ipv4_address: 192.168.11.4
networks:
  zookeeper-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/29